version: "3.7"

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erpnext
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  backend:
    image: frappe/erpnext-worker:version-14
    depends_on:
      - mariadb
      - redis-queue
    environment:
      DB_HOST: mariadb
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_SOCKETIO: redis://redis-socketio:6379

  scheduler:
    image: frappe/erpnext-worker:version-14
    command: bench schedule
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_SOCKETIO: redis://redis-socketio:6379

  nginx:
    image: frappe/erpnext-nginx:version-14
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      FRAPPE_SITE_NAME_HEADER: erp.evoastra.in
      SOCKETIO_PORT: 9000

volumes:
  mariadb-data:
