services:
  - name: erpnext-nginx
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: FRAPPE_SITE_NAME_HEADER
        value: erp.evoastra.in
      - key: SOCKETIO_PORT
        value: 9000
      - key: DB_HOST
        value: mariadb
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: erpnext
      - key: MYSQL_USER
        value: frappe
      - key: MYSQL_PASSWORD
        value: frappe
      - key: REDIS_CACHE
        value: redis://redis-cache:6379
      - key: REDIS_QUEUE
        value: redis://redis-queue:6379
      - key: REDIS_SOCKETIO
        value: redis://redis-socketio:6379

  - name: mariadb
    type: private
    env: docker
    dockerImage: mariadb:10.6
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: erpnext
      - key: MYSQL_USER
        value: frappe
      - key: MYSQL_PASSWORD
        value: frappe

  - name: redis-cache
    type: private
    env: docker
    dockerImage: redis:alpine
    plan: free

  - name: redis-queue
    type: private
    env: docker
    dockerImage: redis:alpine
    plan: free

  - name: redis-socketio
    type: private
    env: docker
    dockerImage: redis:alpine
    plan: free

  - name: erpnext-worker
    type: worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: bench worker
    envVars: *envVarsCommon

  - name: erpnext-scheduler
    type: worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: bench schedule
    envVars: *envVarsCommon
